"""initial schema

Revision ID: 5f3655d94be4
Revises: 
Create Date: 2026-09-05 19:23:37.199762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f3655d94be4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_ref', sa.String(length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('onboarded_at', sa.Date(), nullable=False),
    sa.Column('risk_rating', sa.String(length=16), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_ref'), 'customers', ['customer_ref'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('account_ref', sa.String(length=32), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('expected_monthly_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_ref'), 'accounts', ['account_ref'], unique=True)
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_ref', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_case_status', 'cases', ['status', 'deadline_at'], unique=False)
    op.create_index(op.f('ix_cases_case_ref'), 'cases', ['case_ref'], unique=True)
    op.create_table('alerts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('rule_code', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_case', 'alerts', ['case_id', sa.literal_column('raised_at DESC')], unique=False)
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_chain', 'audit_records', ['case_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_records_case_id'), 'audit_records', ['case_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('case_subjects',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_subjects_case_id'), 'case_subjects', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_subjects_customer_id'), 'case_subjects', ['customer_id'], unique=False)
    op.create_table('evidence_packs',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('builder_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_pack_gin', 'evidence_packs', ['payload'], unique=False, postgresql_using='gin', postgresql_ops={'payload': 'jsonb_path_ops'})
    op.create_index(op.f('ix_evidence_packs_case_id'), 'evidence_packs', ['case_id'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('txn_ref', sa.String(length=32), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('counterparty_ref', sa.String(length=64), nullable=True),
    sa.Column('counterparty_country', sa.String(length=2), nullable=True),
    sa.Column('counterparty_account_ref', sa.String(length=32), nullable=True),
    sa.Column('narrative_text', sa.Text(), nullable=True),
    sa.Column('is_cash', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_txn_account_time', 'transactions', ['account_id', sa.literal_column('executed_at DESC')], unique=False)
    op.create_index('idx_txn_amount', 'transactions', ['amount'], unique=False, postgresql_where=sa.text('amount BETWEEN 8000 AND 10000'))
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_counterparty_account_ref'), 'transactions', ['counterparty_account_ref'], unique=False)
    op.create_index(op.f('ix_transactions_txn_ref'), 'transactions', ['txn_ref'], unique=True)
    op.create_table('evidence_items',
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=False),
    sa.Column('raw_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('source_row_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['evidence_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_pack_id'), 'evidence_items', ['pack_id'], unique=False)
    op.create_table('narratives',
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('generation_mode', sa.String(length=24), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['evidence_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narratives_pack_id'), 'narratives', ['pack_id'], unique=False)
    op.create_table('export_artifacts',
    sa.Column('narrative_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('exported_by', sa.UUID(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_artifacts_narrative_id'), 'export_artifacts', ['narrative_id'], unique=False)
    op.create_table('narrative_sentences',
    sa.Column('narrative_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('w_category', sa.String(length=16), nullable=True),
    sa.Column('grounding_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_sentences_narrative_id'), 'narrative_sentences', ['narrative_id'], unique=False)
    op.create_table('verification_reports',
    sa.Column('narrative_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reports_narrative_id'), 'verification_reports', ['narrative_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_reports_narrative_id'), table_name='verification_reports')
    op.drop_table('verification_reports')
    op.drop_index(op.f('ix_narrative_sentences_narrative_id'), table_name='narrative_sentences')
    op.drop_table('narrative_sentences')
    op.drop_index(op.f('ix_export_artifacts_narrative_id'), table_name='export_artifacts')
    op.drop_table('export_artifacts')
    op.drop_index(op.f('ix_narratives_pack_id'), table_name='narratives')
    op.drop_table('narratives')
    op.drop_index(op.f('ix_evidence_items_pack_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_transactions_txn_ref'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_counterparty_account_ref'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index('idx_txn_amount', table_name='transactions', postgresql_where=sa.text('amount BETWEEN 8000 AND 10000'))
    op.drop_index('idx_txn_account_time', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_evidence_packs_case_id'), table_name='evidence_packs')
    op.drop_index('idx_evidence_pack_gin', table_name='evidence_packs', postgresql_using='gin', postgresql_ops={'payload': 'jsonb_path_ops'})
    op.drop_table('evidence_packs')
    op.drop_index(op.f('ix_case_subjects_customer_id'), table_name='case_subjects')
    op.drop_index(op.f('ix_case_subjects_case_id'), table_name='case_subjects')
    op.drop_table('case_subjects')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_audit_records_case_id'), table_name='audit_records')
    op.drop_index('idx_audit_chain', table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.drop_index('idx_alert_case', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_cases_case_ref'), table_name='cases')
    op.drop_index('idx_case_status', table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_ref'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_customer_ref'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
