"""add narrative_sentence evidence_keys

Revision ID: 82914c64d9d9
Revises: 5f3655d94be4
Create Date: 2026-09-06 12:11:36.429933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82914c64d9d9'
down_revision: Union[str, None] = '5f3655d94be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narrative_sentences', sa.Column('evidence_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('narrative_sentences', 'evidence_keys')
    # ### end Alembic commands ###
